/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type AuthGroupCreateParams struct {

	// Specifies the numeric group identifier.
	Gid int32 `json:"gid,omitempty"`

	// Specifies the members of the group.
	Members []AuthAccessAccessItemFileGroup `json:"members,omitempty"`

	// Specifies the group name.
	Name string `json:"name"`

	// Specifies the security identifier.
	Sid string `json:"sid,omitempty"`
}
