/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type AuthAccessAccessItemFile struct {

	// Specifies absolute path in filesystem.
	EffectivePath string `json:"effective_path,omitempty"`

	// Specifies the permissions that the user has on the file.
	FilePermissions *AuthAccessAccessItemFileFilePermissions `json:"file_permissions,omitempty"`

	// Specifies properties for a persona, which consists of either a 'type' and a 'name' or an 'ID'.
	Group *AuthAccessAccessItemFileGroup `json:"group,omitempty"`

	// Specifies whether path is inside snapshot.
	IsSnapshot bool `json:"is_snapshot,omitempty"`

	// Specifies properties for a persona, which consists of either a 'type' and a 'name' or an 'ID'.
	Owner *AuthAccessAccessItemFileGroup `json:"owner,omitempty"`
}
