/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type AuthRoleExtended struct {

	// Specifies the description of the role.
	Description string `json:"description,omitempty"`

	// Specifies the users or groups that have this role.
	Members []AuthAccessAccessItemFileGroup `json:"members"`

	// Specifies the name of the role.
	Name string `json:"name"`

	// Specifies the privileges granted by this role.
	Privileges []AuthIdNtokenPrivilegeItem `json:"privileges"`

	// Specifies the ID of the role.
	Id string `json:"id"`
}
