/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type AuthAccessAccessItemFileFilePermissions struct {

	// Returns a status message if the Null ACL is set.
	Dacl string `json:"dacl,omitempty"`

	// Returns a status message if the parent directoryhas the delete_child property set for the user.If the delete_child property is set for a user,that user is able to delete the file.the delete_child for the user.
	DeleteChild string `json:"delete_child,omitempty"`

	// Specifies the Access Control Entry (ACE) for the user.
	Expected string `json:"expected,omitempty"`

	// Specifies the mode bits on the file.
	Mode string `json:"mode,omitempty"`

	// Returns a status message if the user owns the file.
	Ownership string `json:"ownership,omitempty"`

	// Specifies a list of the relevant Access Control Entrieswith respect to the user in the share.
	RelevantAces []AuthAccessAccessItemShareSharePermissionsShareRelevantAce `json:"relevant_aces,omitempty"`

	// Specifies the mode bits that are related to the user.
	RelevantMode string `json:"relevant_mode,omitempty"`

	// Returns a status message if the user owns the file.
	Sticky string `json:"sticky,omitempty"`
}
