/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CloudSettingsSettingsCloudPolicyDefaultsCache struct {

	// Specifies cache expiration.
	Expiration int32 `json:"expiration,omitempty"`

	// Specifies cache read ahead type.
	ReadAhead string `json:"read_ahead,omitempty"`

	// Specifies cache type.
	Type_ string `json:"type,omitempty"`
}
