/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CloudSettingsSettings struct {

	// The default filepool policy values for cloudpools.
	CloudPolicyDefaults *CloudSettingsSettingsCloudPolicyDefaults `json:"cloud_policy_defaults,omitempty"`

	// Coefficients in the quadratic function for determining the rest period between successive archive attempts.
	RetryCoefficientArchive string `json:"retry_coefficient_archive,omitempty"`

	// Coefficients in the quadratic function for determining the rest period between successive cache invalidation attempts.
	RetryCoefficientCacheInvalidation string `json:"retry_coefficient_cache_invalidation,omitempty"`

	// Coefficients in the quadratic function for determining the rest period between successive cloud garbage collection attempts.
	RetryCoefficientCloudGarbageCollection string `json:"retry_coefficient_cloud_garbage_collection,omitempty"`

	// Coefficients in the quadratic function for determining the rest period between successive local garbage collection attempts.
	RetryCoefficientLocalGarbageCollection string `json:"retry_coefficient_local_garbage_collection,omitempty"`

	// Coefficients in the quadratic function for determining the rest period between successive read ahead attempts.
	RetryCoefficientReadAhead string `json:"retry_coefficient_read_ahead,omitempty"`

	// Coefficients in the quadratic function for determining the rest period between successive recall attempts.
	RetryCoefficientRecall string `json:"retry_coefficient_recall,omitempty"`

	// Coefficients in the quadratic function for determining the rest period between successive writeback attempts.
	RetryCoefficientWriteback string `json:"retry_coefficient_writeback,omitempty"`

	// Amount of time to wait between successive file archive operations.
	SleepTimeoutArchive *CloudSettingsSettingsSleepTimeoutCloudGarbageCollection `json:"sleep_timeout_archive,omitempty"`

	// Amount of time to wait between successive file cache_invalidation operations.
	SleepTimeoutCacheInvalidation *CloudSettingsSettingsSleepTimeoutCloudGarbageCollection `json:"sleep_timeout_cache_invalidation,omitempty"`

	// Amount of time to wait between successive file cloud garbage collection operations.
	SleepTimeoutCloudGarbageCollection *CloudSettingsSettingsSleepTimeoutCloudGarbageCollection `json:"sleep_timeout_cloud_garbage_collection,omitempty"`

	// Amount of time to wait between successive file local garbage collection operations.
	SleepTimeoutLocalGarbageCollection *CloudSettingsSettingsSleepTimeoutCloudGarbageCollection `json:"sleep_timeout_local_garbage_collection,omitempty"`

	// Amount of time to wait between successive file read ahead operations.
	SleepTimeoutReadAhead *CloudSettingsSettingsSleepTimeoutCloudGarbageCollection `json:"sleep_timeout_read_ahead,omitempty"`

	// Amount of time to wait between successive file recall operations.
	SleepTimeoutRecall *CloudSettingsSettingsSleepTimeoutCloudGarbageCollection `json:"sleep_timeout_recall,omitempty"`

	// Amount of time to wait between successive file writeback operations.
	SleepTimeoutWriteback *CloudSettingsSettingsSleepTimeoutCloudGarbageCollection `json:"sleep_timeout_writeback,omitempty"`
}
