/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CloudAccessCluster struct {

	// A list of accounts created on the cluster with this guid
	Accounts []string `json:"accounts,omitempty"`

	// Whether the guid is that of the current (local) cluster
	Current bool `json:"current,omitempty"`

	// A cluster guid indicating the birth place of one or more accounts or policies on this cluster
	Guid string `json:"guid,omitempty"`

	// A cluster guid indicating the birth place of one or more accounts or policies on this cluster
	Id string `json:"id,omitempty"`

	// The name of the cluster from which the above guid originated
	Name string `json:"name,omitempty"`

	// A list of policies created on the cluster with this guid
	Policies []string `json:"policies,omitempty"`

	// Whether the guid has access to the cloud
	State string `json:"state,omitempty"`

	// The name of the cluster from which the above guid was synced
	SyncedFrom string `json:"synced_from,omitempty"`
}
