/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CloudJobJobEngineJob struct {

	// ID of the related job engine job
	Id int32 `json:"id,omitempty"`

	// The state of the related job engine job
	State string `json:"state,omitempty"`
}
