/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// A cloud job for archiving or recalling files
type CloudJob struct {

	// Whether to apply to the given operation type or to all jobs of the given operation type
	All bool `json:"all,omitempty"`

	// The desired state of the job or operation
	State string `json:"state,omitempty"`
}
