/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ClusterNodesOnefsVersion struct {

	Bugfix int32 `json:"bugfix,omitempty"`

	Maintenance int32 `json:"maintenance,omitempty"`

	Major int32 `json:"major,omitempty"`

	Minor int32 `json:"minor,omitempty"`

	// hex representation of the OneFS version integer.
	Version string `json:"version,omitempty"`
}
