/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ClusterConfigDevice struct {

	// Device ID.
	Devid int32 `json:"devid"`

	// Device GUID.
	Guid string `json:"guid"`

	// If true, this node is online and communicating with the local node and every other node with the is_up property normally.  If false, this node is not currently communicating with the local node or other nodes with the is_up property.  It may be shut down, rebooting, disconnected from the backend network, or connected only to other nodes.
	IsUp bool `json:"is_up"`

	// Device logical node number.
	Lnn int32 `json:"lnn"`
}
