/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// The settings necessary to start an upgrade.
type ClusterUpgradeItem struct {

	// The location (path) of the upgrade image which must be within /ifs.
	InstallImagePath string `json:"install_image_path,omitempty"`

	// The nodes (to be) scheduled for upgrade ordered by queue position number. Null if the cluster_state is 'partially upgraded' or upgrade_type is 'simultaneous'. One of the following values: [<lnn-1>, <lnn-2>, ... ], 'All', null
	NodesToRollingUpgrade []int32 `json:"nodes_to_rolling_upgrade,omitempty"`

	// Used to indicate that the pre-upgrade check should be skipped
	SkipOptional bool `json:"skip_optional,omitempty"`

	// The type of upgrade to perform. One of the following values: 'rolling', 'simultaneous'
	UpgradeType string `json:"upgrade_type,omitempty"`
}
