/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// The settings necessary to start a firmware upgrade.
type ClusterFirmwareUpgradeItem struct {

	// Exclude the specified devices in the firmware upgrade.
	ExcludeDevice string `json:"exclude_device,omitempty"`

	// Exclude the specified device type in the firmware upgrade.
	ExcludeType string `json:"exclude_type,omitempty"`

	// Include the specified devices in the firmware upgrade.
	IncludeDevice string `json:"include_device,omitempty"`

	// Include the specified device type in the firmware upgrade.
	IncludeType string `json:"include_type,omitempty"`

	// Do not burn the firmware.
	NoBurn bool `json:"no_burn,omitempty"`

	// Do not reboot the node after an upgrade
	NoReboot bool `json:"no_reboot,omitempty"`

	// Do not verify the firmware upgrade after an upgrade.
	NoVerify bool `json:"no_verify,omitempty"`

	// The nodes scheduled for upgrade. Order in array determines queue position number. 'All' and null option will upgrade all nodes in <lnn> order.
	NodesToUpgrade []int32 `json:"nodes_to_upgrade,omitempty"`
}
