/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// A software patch that can be applied to OneFS.
type ClusterPatchPatch struct {

	// The path location of the patch file.
	Location string `json:"location,omitempty"`

	// The id or filename of the patch to install.
	Patch string `json:"patch"`
}
