/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ClusterFirmwareStatusNodeDevice struct {

	// The name of the device.
	Device string `json:"device,omitempty"`

	// Is the firmware up-to-date for this component.
	Mismatch bool `json:"mismatch,omitempty"`

	// The target firmware version.
	TargetVersion string `json:"target_version,omitempty"`

	// The device type.
	Type_ string `json:"type,omitempty"`

	// The current state of the firmware upgrade for this component. One of the following values: 'queued', 'upgrading', 'upgraded', 'error'. or 'null'.'null' indicates that the upgrade status is unknown.
	UpgradeStatus string `json:"upgrade_status,omitempty"`

	// The current firmware version.
	Version string `json:"version,omitempty"`
}
