/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ClusterConfigTimezone struct {

	// Timezone abbreviation.
	Abbreviation string `json:"abbreviation,omitempty"`

	// Customer timezone information.
	Custom string `json:"custom,omitempty"`

	// Timezone full name.
	Name string `json:"name,omitempty"`

	// Timezone hierarchical name.
	Path string `json:"path,omitempty"`
}
