/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// The settings necessary to start a pre-upgrade assessment.
type ClusterAssessItem struct {

	// The location (path) of the upgrade image which must be within /ifs.
	InstallImagePath string `json:"install_image_path,omitempty"`
}
