/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ClusterConfigOnefsVersion struct {

	// OneFS build string.
	Build string `json:"build"`

	// Cluster copyright information.
	Copyright string `json:"copyright"`

	// Timestamp of release date.
	Reldate int32 `json:"reldate"`

	// Kernel release number.
	Release string `json:"release"`

	// OneFS build number.
	Revision string `json:"revision"`

	// Kernel release type.
	Type_ string `json:"type"`

	// Kernel full version information.
	Version string `json:"version"`
}
