/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ClusterPatchPatchesPatch struct {

	// A long comment about the patch.
	Comment string `json:"comment,omitempty"`

	// Other patches that this patch conflicts with.
	Conflicts []string `json:"conflicts,omitempty"`

	// Other patches that this patch depends on.
	Dependencies []string `json:"dependencies,omitempty"`

	// A short description of the patch.
	Description string `json:"description,omitempty"`

	// The files contained in this patch.
	Files []ClusterPatchPatchesPatchFile `json:"files,omitempty"`

	// A unique identifier for the patch.
	Id string `json:"id,omitempty"`

	// The name of the patch.
	Name string `json:"name,omitempty"`

	// The nodes that this patch is installed on.
	Nodes []int32 `json:"nodes,omitempty"`

	// Describes the reboot requirements
	Reboot string `json:"reboot,omitempty"`

	// The services affected during the patch deployment
	Services []ClusterPatchPatchesPatchService `json:"services,omitempty"`

	// The intallation status of this patch on the cluster.
	Status string `json:"status,omitempty"`
}
