/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// Cluster contact info settings.
type ClusterOwner struct {

	// Cluster owner company name.
	Company string `json:"company,omitempty"`

	// Cluster owner location.
	Location string `json:"location,omitempty"`

	// Cluster owner primary email address.
	PrimaryEmail string `json:"primary_email,omitempty"`

	// Cluster owner primary contact name.
	PrimaryName string `json:"primary_name,omitempty"`

	// Cluster owner primary contact phone number 1.
	PrimaryPhone1 string `json:"primary_phone1,omitempty"`

	// Cluster owner primary contact phone number 2.
	PrimaryPhone2 string `json:"primary_phone2,omitempty"`

	// Cluster owner secondary email address.
	SecondaryEmail string `json:"secondary_email,omitempty"`

	// Cluster owner secondary contact name.
	SecondaryName string `json:"secondary_name,omitempty"`

	// Cluster owner secondary contact phone number 1.
	SecondaryPhone1 string `json:"secondary_phone1,omitempty"`

	// Cluster owner secondary contact phone number 2.
	SecondaryPhone2 string `json:"secondary_phone2,omitempty"`
}
