/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// Retry the last upgrade action, in-case the previous attempt failed.
type ClusterRetryLastActionItem struct {

	// List of the nodes or \"all\" where the last upgrade action can be retried.
	Nodes []int32 `json:"nodes,omitempty"`
}
