/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CompatibilitiesSsdAvailableAvailableItem struct {

	// The node class of an ssd compatibility
	Class1 string `json:"class_1"`

	// The id of this ssd compatibility
	Id int32 `json:"id"`
}
