/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CreateSnapshotChangelistResponse struct {

	// The ID of the job which created the changelist.
	JobId int32 `json:"job_id"`

	// Number of LIN entries in changelist.
	NumEntries int32 `json:"num_entries,omitempty"`

	// Root path of all LINs in changelist.
	RootPath string `json:"root_path"`

	// The lower snapid used to compute the changelist.
	Snap1 int32 `json:"snap1"`

	// The higher snapid used to compute the changelist.
	Snap2 int32 `json:"snap2"`

	// Status of changelist.
	Status string `json:"status"`
}
