/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CreateCompatibilitiesClassActiveItemResponse struct {

	// A list of all merges that will occur given this compatibility operation
	Merges []CreateCompatibilitiesClassActiveItemResponseMerge `json:"merges,omitempty"`

	// A string describing the effects of the compatibility operation.
	Message string `json:"message"`

	// A list of all splits that will occur given this compatibility operation
	Splits []CreateCompatibilitiesClassActiveItemResponseSplit `json:"splits,omitempty"`
}
