/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type CreateCompatibilitiesClassActiveItemResponseMerge struct {

	// The nodepool ids that will be merged
	Ids []int32 `json:"ids"`

	// The nodepool names that will be merged, in the sameorder as the ids
	Names []string `json:"names"`

	// The name of the nodepool all others will merge into
	ResultName string `json:"result_name"`
}
