/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type DrivesDriveFirmwareUpdateNodeStatus struct {

	// The number of drives that did not successfully complete firmware updates update on the node.
	Failed int32 `json:"failed,omitempty"`

	// Time when drive firmware update finished on node.
	FinishTime string `json:"finish_time,omitempty"`

	// Number of drives remaining to be updated on node.
	Remaining int32 `json:"remaining,omitempty"`

	// Time when drive firmware update started on node.
	StartTime string `json:"start_time,omitempty"`

	// Overall status of this nodes firmware updates.
	Status string `json:"status,omitempty"`

	// The number of drives that completed firmware updates on the node.
	Updated int32 `json:"updated,omitempty"`
}
