/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// Drive firmware update information.
type DrivesDriveFirmwareUpdateItem struct {

	// Indicates whether this is a cluster wide drive firwmare update or not
	ClusterWide bool `json:"cluster_wide"`
}
