/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type EventSettingsSettingsMaintenance struct {

	// Duration of maintenance period in seconds.
	Duration int32 `json:"duration,omitempty"`

	// Start of maintenance period.
	Start int32 `json:"start,omitempty"`
}
