/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type FilepoolPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem struct {

	// Indicates whether the existence of an attribute indicates a match (valid only with 'type' = 'custom_attribute')
	AttributeExists bool `json:"attribute_exists,omitempty"`

	// True to match files recursively under the given path. (valid only with 'type' = 'path')
	BeginsWith bool `json:"begins_with,omitempty"`

	// True to indicate case sensitivity when comparing file attributes (valid only with 'type' = 'name' or 'type' = 'path')
	CaseSensitive bool `json:"case_sensitive,omitempty"`

	// File attribute field name to be compared in a custom comparison (valid only with 'type' = 'custom_attribute')
	Field string `json:"field,omitempty"`

	// The comparison operator to use while comparing an attribute with its value
	Operator string `json:"operator,omitempty"`

	// The file attribute to be compared to a given value
	Type_ string `json:"type"`

	// Size unit value. One of 'B','KB','MB','GB','TB','PB','EB' (valid only with 'type' = 'size')
	Units string `json:"units,omitempty"`

	// Whether time units refer to a calendar date and time (e.g., Jun 3, 2009) or a relative duration (e.g., 2 weeks) (valid only with 'type' in {accessed_time, birth_time, changed_time or metadata_changed_time}
	UseRelativeTime bool `json:"use_relative_time,omitempty"`

	// The value to be compared against a file attribute
	Value string `json:"value,omitempty"`
}
