/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type FilepoolPolicyExtended struct {

	// A list of actions to be taken for matching files
	Actions []FilepoolDefaultPolicyDefaultPolicyAction `json:"actions,omitempty"`

	// The order in which this policy should be applied (relative to other policies)
	ApplyOrder int32 `json:"apply_order,omitempty"`

	// The guid assigned to the cluster on which the account was created
	BirthClusterId string `json:"birth_cluster_id,omitempty"`

	// A description for this policy
	Description string `json:"description,omitempty"`

	// The file matching rules for this policy
	FileMatchingPattern *FilepoolPolicyFileMatchingPattern `json:"file_matching_pattern,omitempty"`

	// A unique identifier for this policy
	Id int32 `json:"id,omitempty"`

	// A unique name for this policy
	Name string `json:"name,omitempty"`

	// Indicates whether this policy is in a good state (\"OK\") or disabled (\"disabled\")
	State string `json:"state,omitempty"`

	// Gives further information to describe the state of this policy
	StateDetails string `json:"state_details,omitempty"`
}
