/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// A default filepool policy object
type FilepoolDefaultPolicy struct {

	// A default filepool policy object
	DefaultPolicy *FilepoolDefaultPolicyDefaultPolicy `json:"default-policy,omitempty"`
}
