/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type HistogramStatBy struct {

	// Unix Epoch time of start of results collection job.
	BeginTime int32 `json:"begin_time"`

	// Histogram breakout data according to breakout parameter.
	Breakouts []HistogramStatByBreakout `json:"breakouts"`

	// Total length of the result list.
	ResultLength int32 `json:"result_length"`
}
