/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type HistoryFileStatistic struct {

	// Nodes allocated for the sync action.
	Allocated int32 `json:"allocated"`

	// An ID for a single performance report.
	Id int32 `json:"id"`

	// Sync action limit.
	Limit int32 `json:"limit"`

	// Timestamp for the performance report.
	Timestamp int32 `json:"timestamp"`

	// Total usage for the performance report.
	Total int32 `json:"total"`
}
