/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type JobStatisticsJobNodeWorker struct {

	// The sleep-to-work ratio of this worker; how much time it spends sleeping compared to working.
	Stw float32 `json:"stw,omitempty"`

	// A representation of the task the worker is currently processing; not intended to be read by humans.
	Task string `json:"task,omitempty"`

	// A representation of the most recent task result produced by the worker; not intended to be read by humans.
	TaskResult string `json:"task_result,omitempty"`

	// The worker ID.
	Worker int32 `json:"worker"`
}
