/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type JobJobDomainmarkParams struct {

	// Whether this is a delete operation.
	Delete bool `json:"delete,omitempty"`

	// Base IFS path to associate with the domain.
	Root string `json:"root"`

	// The type of domain.
	Type_ string `json:"type"`
}
