/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type JobStatisticsJobNode struct {

	// 
	Cpu *JobStatisticsJobNodeCpu `json:"cpu"`

	// 
	Io *JobStatisticsJobNodeIo `json:"io"`

	// 
	Memory *JobStatisticsJobNodeMemory `json:"memory"`

	// The devid of the node.
	Node int32 `json:"node"`

	// The process ID of the job on this node.
	Pid int32 `json:"pid"`

	// The number of workers for this job on this node.
	TotalWorkers int32 `json:"total_workers"`

	Workers []JobStatisticsJobNodeWorker `json:"workers"`
}
