/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type JobEvent struct {

	// Event flags.
	Flags string `json:"flags"`

	// A string representation of the type of the data value.
	FmtType string `json:"fmt_type"`

	// Job event ID.
	Id int32 `json:"id"`

	// Job ID.
	JobId int32 `json:"job_id"`

	// Job Type.
	JobType string `json:"job_type"`

	// Event key name.
	Key string `json:"key"`

	// Job phase number at time of event.
	Phase int32 `json:"phase"`

	// An integer representation of the type of the data value.
	RawType int32 `json:"raw_type"`

	// Time of event in Unix epoch seconds.
	Time int32 `json:"time"`

	// Event value.
	Value string `json:"value,omitempty"`
}
