/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type JobJobCreateParams struct {

	// Whether or not to queue the job if one of the same type is already running or queued.
	AllowDup bool `json:"allow_dup,omitempty"`

	// 
	AvscanParams *JobJobAvscanParams `json:"avscan_params,omitempty"`

	// 
	ChangelistcreateParams *JobJobChangelistcreateParams `json:"changelistcreate_params,omitempty"`

	// 
	DomainmarkParams *JobJobDomainmarkParams `json:"domainmark_params,omitempty"`

	// For jobs which take paths, the IFS paths to pass to the job.
	Paths []string `json:"paths"`

	// Impact policy of this job instance.
	Policy string `json:"policy,omitempty"`

	// 
	PrepairParams *JobJobPrepairParams `json:"prepair_params,omitempty"`

	// Priority of this job instance; lower numbers preempt higher numbers.
	Priority int32 `json:"priority,omitempty"`

	// 
	SmartpoolstreeParams *JobJobSmartpoolstreeParams `json:"smartpoolstree_params,omitempty"`

	// 
	SnaprevertParams *JobJobSnaprevertParams `json:"snaprevert_params,omitempty"`

	// Job type to queue.
	Type_ string `json:"type"`
}
