/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type LicenseGenerateHardwareItem struct {

	// Licensed terabyte (TB, 10^12 bytes) drive capacity allocated as storage associated with tier. Included if tier is not NONINF and license is not a base only license.
	DriveCapacity int32 `json:"drive_capacity,omitempty"`

	// Licensed number of nodes in this tier.
	NodeCount int32 `json:"node_count,omitempty"`

	// Licensed number of nodes of this tier that contain self-encrypting drives. Included only if license is ONEFS and tier is not NONINF.
	NodesWithSedsCount int32 `json:"nodes_with_seds_count,omitempty"`

	// OneFS hardware tier. Tier is a number, NONINF, or NO_TIER. NONINF indicates a non infinity tier. NO_TIER indicates a license that is not tier based.
	Tier string `json:"tier,omitempty"`
}
