/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type LicenseGenerate struct {

	// Array of licenses included in activation file.
	ActivatedLicenseList []string `json:"activated_license_list,omitempty"`

	// Contents of licensing activation file.
	Activation string `json:"activation,omitempty"`

	// Array of licenses included in activation file.
	Hardware []LicenseGenerateHardwareItem `json:"hardware,omitempty"`

	// An array of licenses not included in activation file.
	NotActivatedLicenseList []string `json:"not_activated_license_list,omitempty"`
}
