/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type LicenseLicense struct {

	// Number of days since a license expired.
	DaysSinceExpiry int32 `json:"days_since_expiry,omitempty"`

	// Number of days before a license expires.
	DaysToExpiry int32 `json:"days_to_expiry,omitempty"`

	// Date of license expiry. Format is YYYY-MM-DD. It is not included if there is no expiration. Feature is considered expired at end of this day. The cluster time is used to determine expiry.
	Expiration string `json:"expiration,omitempty"`

	// True when we are generating an alert that this feature has expired.
	ExpiredAlert bool `json:"expired_alert"`

	// True when we are generating an alert that this feature is expiring.
	ExpiringAlert bool `json:"expiring_alert"`

	// Name of the licensed feature.
	Id string `json:"id"`

	// Name of the licensed feature.
	Name string `json:"name"`

	// Current status of the license.
	Status string `json:"status"`

	// Tiered License details.
	Tiers []LicenseLicenseTier `json:"tiers"`
}
