/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type LicenseLicenseTierEntitlementsExceededAlert struct {

	// Current usage.
	Current int32 `json:"current,omitempty"`

	// Alert type. The unit of measure for the current and licensed fields for capacity is terabytes. For nodes_with_seds_count, it is the number of nodes that have one or more self-encrypting drives.
	IssueType string `json:"issue_type"`

	// Licensed amount.
	Licensed int32 `json:"licensed,omitempty"`
}
