/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type MappingUsersLookupMappingItem struct {

	Groups []MappingUsersLookupMappingItemGroup `json:"groups,omitempty"`

	ObjectHistory []AuthGroupObjectHistoryItem `json:"object_history,omitempty"`

	Privileges []AuthIdNtokenPrivilegeItem `json:"privileges,omitempty"`

	// Specifies the configuration properties for a user.
	User *MappingUsersLookupMappingItemUser `json:"user,omitempty"`

	Zid int32 `json:"zid,omitempty"`

	Zone string `json:"zone,omitempty"`
}
