/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type MappingIdentityTargetCreateParams struct {

	// Identity is preferred on-disk.
	OnDisk bool `json:"on_disk,omitempty"`

	// Specifies properties for a persona, which consists of either a 'type' and a 'name' or an 'ID'.
	Target *AuthAccessAccessItemFileGroup `json:"target"`

	// Origin of identity mapping.
	Type_ string `json:"type,omitempty"`
}
