/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type MappingUsersRulesRules struct {

	// Specifies the default UNIX user information that can be applied if the final credentials do not have valid UID and GID information.
	Parameters *MappingUsersRulesRulesParameters `json:"parameters,omitempty"`

	// Specifies the list of user mapping rules.
	Rules []MappingUsersRulesRule `json:"rules,omitempty"`
}
