/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type NdmpContextsBreContext struct {

	// Unique ID of NDMP BRE context
	BreContextId string `json:"bre_context_id,omitempty"`

	// Unique display id.
	Id string `json:"id,omitempty"`
}
