/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// Specifies properties for a persona, which consists of either a 'type' and a 'name' or an 'ID'.
type NfsSettingsExportSettingsMapAllSecondaryGroups struct {

	// Specifies the serialized form of a persona, which can be 'UID:0', 'USER:name', 'GID:0', 'GROUP:wheel', or 'SID:S-1-1'.
	Id string `json:"id,omitempty"`

	// Specifies the persona name, which must be combined with a type.
	Name string `json:"name,omitempty"`

	// Specifies the type of persona, which must be combined with a name.
	Type_ string `json:"type,omitempty"`
}
