/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type NodeDrivesNodeDriveFirmware struct {

	// This drive's current firmware revision
	CurrentFirmware string `json:"current_firmware,omitempty"`

	// This drive's desired firmware revision.
	DesiredFirmware string `json:"desired_firmware,omitempty"`
}
