/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type NodeStatusNodeCapacityItem struct {

	// Total device storage bytes.
	Bytes int32 `json:"bytes,omitempty"`

	// Total device count.
	Count int32 `json:"count,omitempty"`

	// Device type.
	Type_ string `json:"type,omitempty"`
}
