/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type NodeDrivesPurposelistError struct {

	// The general meaning of the status code.
	Code string `json:"code,omitempty"`

	// Logical node number of the node reporting this error.
	Lnn int32 `json:"lnn,omitempty"`

	// More detailed description of the error.
	Message string `json:"message,omitempty"`

	// HTTP Status code returned by this node.
	Status int32 `json:"status,omitempty"`
}
