/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type NodeDrivesPurposelistNodePurpose struct {

	// String representation of this purpose for API use.
	Purpose string `json:"purpose,omitempty"`

	// A description of this purpose.
	PurposeDescription string `json:"purpose_description,omitempty"`
}
