/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type NodeDriveconfigNodeReboot struct {

	// Indicates whether or not to reboot the node due to a lost chassis.
	ChassisLoss bool `json:"chassis_loss,omitempty"`

	// Indicates whether or not to reboot the node if no drives are present.
	NonePresent bool `json:"none_present,omitempty"`
}
