/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type NtpSettingsSettings struct {

	// Number of nodes that will contact the NTP servers.
	Chimers int32 `json:"chimers,omitempty"`

	// Node number (LNN) for nodes excluded from chimer duty.
	Excluded []string `json:"excluded,omitempty"`

	// Path to NTP key file within /ifs.
	KeyFile string `json:"key_file,omitempty"`
}
