/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ProgressGlobalProgress struct {

	// Specifies the time of the last logged audit protocol event time on the cluster.
	ProtocolAuditLatestLogTime int32 `json:"protocol_audit_latest_log_time,omitempty"`

	// Specifies the time of the oldest protocol audit event consumed by the CEE forwarder on the cluster.
	ProtocolAuditOldestCeeTime int32 `json:"protocol_audit_oldest_cee_time,omitempty"`

	// Specifies the time of the oldest protocol audit event consumed by the Syslog forwarder on the cluster.
	ProtocolAuditOldestSyslogTime int32 `json:"protocol_audit_oldest_syslog_time,omitempty"`
}
