/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ProvidersLocalLocalItem struct {

	// If true, enables authentication and identity management through the authentication provider.
	Authentication bool `json:"authentication,omitempty"`

	// Automatically creates the home directory on the first login.
	CreateHomeDirectory bool `json:"create_home_directory,omitempty"`

	// Specifies the path to the home directory template.
	HomeDirectoryTemplate string `json:"home_directory_template,omitempty"`

	// Specifies the local provider ID.
	Id string `json:"id,omitempty"`

	// Specifies the length of time in seconds that an account will be inaccessible after multiple failed login attempts.
	LockoutDuration int32 `json:"lockout_duration,omitempty"`

	// Specifies the number of failed login attempts necessary before an account is locked.
	LockoutThreshold int32 `json:"lockout_threshold,omitempty"`

	// Specifies the duration of time in seconds in which the number of failed attempts set in the 'lockout_threshold' parameter must be made before an account is locked.
	LockoutWindow int32 `json:"lockout_window,omitempty"`

	// Specifies the login shell path.
	LoginShell string `json:"login_shell,omitempty"`

	// Specifies the domain for this provider through which users and groups are qualified.
	MachineName string `json:"machine_name,omitempty"`

	// Specifies the maximum password age in seconds.
	MaxPasswordAge int32 `json:"max_password_age,omitempty"`

	// Specifies the minimum password age in seconds.
	MinPasswordAge int32 `json:"min_password_age,omitempty"`

	// Specifies the minimum password length.
	MinPasswordLength int32 `json:"min_password_length,omitempty"`

	// Specifies the local provider name.
	Name string `json:"name,omitempty"`

	// Specifies the conditions required for a password.
	PasswordComplexity []string `json:"password_complexity,omitempty"`

	// Specifies the number of previous passwords to store.
	PasswordHistoryLength int32 `json:"password_history_length,omitempty"`

	// Specifies the time in seconds remaining before a user will be prompted for a password change.
	PasswordPromptTime int32 `json:"password_prompt_time,omitempty"`

	// Specifies the status of the provider.
	Status string `json:"status,omitempty"`

	// If true, indicates that this provider instance was created by OneFS and cannot be removed.
	System bool `json:"system,omitempty"`
}
