/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ProvidersSummaryProviderInstanceConnection struct {

	// Specifies the IP address of the provider.
	Address string `json:"address,omitempty"`

	// Specifies the last time the server was contacted.
	LastUsed string `json:"last_used,omitempty"`

	// Specifies the fully qualified domain name of the server.
	Server string `json:"server,omitempty"`
}
