/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type QuotaQuotasSummarySummary struct {

	// Total number of quotas.
	Count int32 `json:"count"`

	// Total number of default-group quotas.
	DefaultGroupQuotasCount int32 `json:"default_group_quotas_count"`

	// Total number of default-user quotas.
	DefaultUserQuotasCount int32 `json:"default_user_quotas_count"`

	// Total number of directory quotas.
	DirectoryQuotasCount int32 `json:"directory_quotas_count"`

	// Total number of -group quotas.
	GroupQuotasCount int32 `json:"group_quotas_count"`

	// Total number of user and group totals that are linked.
	LinkedQuotasCount int32 `json:"linked_quotas_count"`

	// Total number of user quotas.
	UserQuotasCount int32 `json:"user_quotas_count"`
}
