/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ReportsScansReport struct {

	// The number of bytes sent to the virus definition server to be scanned.
	BytesSent int32 `json:"bytes_sent,omitempty"`

	// The length of time the job ran for.
	Duration int32 `json:"duration,omitempty"`

	End int32 `json:"end,omitempty"`

	// The number of files scanned.
	Files int32 `json:"files,omitempty"`

	// A unique identifier for the report.
	Id string `json:"id,omitempty"`

	// The number of infections found.
	Infections int32 `json:"infections,omitempty"`

	JobId int32 `json:"job_id,omitempty"`

	// The id of the policy that this scan job executed.
	PolicyId string `json:"policy_id,omitempty"`

	// The cumulative size of the files scanned.
	Size int32 `json:"size,omitempty"`

	Start int32 `json:"start,omitempty"`

	// The state of the job.
	Status string `json:"status,omitempty"`
}
