/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type ReportAboutReport struct {

	// Whether report was manually requested (live) or scheduled.
	Generated string `json:"generated"`

	// The system ID given to the report.
	Id string `json:"id"`

	// Unix epoch time the report was taken.
	Time int32 `json:"time"`

	// Whether this is a summary or detail report.
	Type_ string `json:"type"`
}
