/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// Specifies the Kerberos settings for domain-realm mappings.
type SettingsKrb5Domain struct {

	// Specifies the name of the realm.
	Realm string `json:"realm,omitempty"`
}
