/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SettingsKrb5RealmCreateParams struct {

	// Specifies the administrative server hostname.
	AdminServer string `json:"admin_server,omitempty"`

	// Specifies the default domain mapped to the realm.
	DefaultDomain string `json:"default_domain,omitempty"`

	// If true, indicates that the realm is the default.
	IsDefaultRealm bool `json:"is_default_realm,omitempty"`

	// Specifies the list of KDC hostnames.
	Kdc []string `json:"kdc,omitempty"`

	// Specifies the name of the realm.
	Realm string `json:"realm"`
}
