/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SettingsAclsAclPolicySettings struct {

	// Access checks (chmod, chown).
	Access string `json:"access,omitempty"`

	// Displayed mode bits.
	Calcmode string `json:"calcmode,omitempty"`

	// Approximate group mode bits when ACL exists.
	CalcmodeGroup string `json:"calcmode_group,omitempty"`

	// Approximate owner mode bits when ACL exists.
	CalcmodeOwner string `json:"calcmode_owner,omitempty"`

	// chmod on files with existing ACLs.
	Chmod string `json:"chmod,omitempty"`

	// chmod (007) on files with existing ACLs.
	Chmod007 string `json:"chmod_007,omitempty"`

	// ACLs created on directories by UNIX chmod.
	ChmodInheritable string `json:"chmod_inheritable,omitempty"`

	// chown/chgrp on files with existing ACLs.
	Chown string `json:"chown,omitempty"`

	// ACL creation over SMB.
	CreateOverSmb string `json:"create_over_smb,omitempty"`

	//  Read only DOS attribute.
	DosAttr string `json:"dos_attr,omitempty"`

	// Group owner inheritance.
	GroupOwnerInheritance string `json:"group_owner_inheritance,omitempty"`

	// Treatment of 'rwx' permissions.
	Rwx string `json:"rwx,omitempty"`

	// Synthetic 'deny' ACEs.
	SyntheticDenies string `json:"synthetic_denies,omitempty"`

	// Access check (utimes)
	Utimes string `json:"utimes,omitempty"`
}
