/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SettingsKrb5DefaultsKrb5Settings struct {

	// If true, allow the use of DES encryption
	AllowWeakCrypto bool `json:"allow_weak_crypto,omitempty"`

	// If true, always attempts to preauthenticate to the domain controller.
	AlwaysSendPreauth bool `json:"always_send_preauth,omitempty"`

	// Specifies the realm for unqualified names.
	DefaultRealm string `json:"default_realm,omitempty"`

	// If true, find KDCs through the DNS.
	DnsLookupKdc bool `json:"dns_lookup_kdc,omitempty"`

	// If true, find realm names through the DNS.
	DnsLookupRealm bool `json:"dns_lookup_realm,omitempty"`
}
