/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SettingsMapping struct {

	// Specifies the properties for global authentication setting.
	MappingSettings *SettingsMappingMappingSettings `json:"mapping_settings,omitempty"`
}
