/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SmbSettingsGlobalSettingsAuditGlobalSaclItem struct {

	// Determines if audit is performed on success or failure.
	Flags string `json:"flags"`

	// Specifies the array of filesystem rights that are governed.
	Permission []string `json:"permission"`
}
