/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SmbLogLevelFiltersFilter struct {

	// Unique ID of the log filter.
	Id int32 `json:"id,omitempty"`

	// Array of client IP addresses to filter against.
	IpAddrs []string `json:"ip_addrs,omitempty"`

	// Logging level of the filter.
	Level string `json:"level"`

	// Array of SMB operations to filter against.
	Ops []string `json:"ops,omitempty"`
}
