/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SmbSession struct {

	// Number of seconds since session start.
	ActiveTime int32 `json:"active_time"`

	// Client type.
	ClientType string `json:"client_type"`

	// Client internet address.
	Computer string `json:"computer"`

	// True if session is encrypted.
	Encryption bool `json:"encryption"`

	// True for guest logins.
	GuestLogin bool `json:"guest_login"`

	// The session ID.
	Id int32 `json:"id"`

	// Number of seconds since last client operation.
	IdleTime int32 `json:"idle_time"`

	// Number of files open by client.
	Openfiles int32 `json:"openfiles"`

	// Local user name.
	User string `json:"user"`
}
