/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SmbOpenfile struct {

	// Path of file within /ifs.
	File string `json:"file"`

	// The file ID.
	Id int32 `json:"id"`

	// Number of locks user holds on file.
	Locks int32 `json:"locks"`

	// The user's permissions on file.
	Permissions []string `json:"permissions"`

	// User holding file open.
	User string `json:"user"`
}
