/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SnapshotSettingsExtended struct {

	// True if the scheduled snapshot creation services is on.
	Autocreate bool `json:"autocreate,omitempty"`

	// True if the scheduled snapshot deletion services is on.
	Autodelete bool `json:"autodelete,omitempty"`

	// Global switch for other accessible and visible settings.
	GlobalVisibleAccessible bool `json:"global_visible_accessible,omitempty"`

	// True if root .snapshot directory is accessible locally.
	LocalRootAccessible bool `json:"local_root_accessible,omitempty"`

	// True if root .snapshot directory is visible locally.
	LocalRootVisible bool `json:"local_root_visible,omitempty"`

	// True if sub-directory .snapshot directory is accessible locally.
	LocalSubdirAccessible bool `json:"local_subdir_accessible,omitempty"`

	// True if root .snapshot directory is accessible over NFS.
	NfsRootAccessible bool `json:"nfs_root_accessible,omitempty"`

	// True if root .snapshot directory is visible over NFS.
	NfsRootVisible bool `json:"nfs_root_visible,omitempty"`

	// True if sub-directory .snapshot directory is accessible over NFS.
	NfsSubdirAccessible bool `json:"nfs_subdir_accessible,omitempty"`

	// Percentage of space to reserve for snapshots.
	Reserve float32 `json:"reserve,omitempty"`

	// True if the system allows snapshot creation.
	Service bool `json:"service,omitempty"`

	// True if root .snapshot directory is accessible over SMB.
	SmbRootAccessible bool `json:"smb_root_accessible,omitempty"`

	// True if root .snapshot directory is visible over SMB.
	SmbRootVisible bool `json:"smb_root_visible,omitempty"`

	// True if sub-directory .snapshot directory is accessible over SMB.
	SmbSubdirAccessible bool `json:"smb_subdir_accessible,omitempty"`
}
