/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SnapshotAliasExtended struct {

	// The Unix Epoch time the snapshot alias was created.
	Created int32 `json:"created"`

	// The system ID given to the snapshot alias.
	Id int32 `json:"id"`

	// The user or system supplied snapshot alias name.
	Name string `json:"name"`

	// The ID of the snapshot pointed to.
	TargetId int32 `json:"target_id"`

	// The name of the snapshot pointed to.
	TargetName string `json:"target_name"`
}
