/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SnapshotSnapshot struct {

	// Alias name to create for this snapshot. If null, remove any alias.
	Alias string `json:"alias,omitempty"`

	// The Unix Epoch time the snapshot will expire and be eligible for automatic deletion.
	Expires int32 `json:"expires,omitempty"`

	// The user or system supplied snapshot name. This will be null for snapshots pending delete.
	Name string `json:"name,omitempty"`
}
