/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SnapshotLocksExtended struct {

	Locks []SnapshotLockExtended `json:"locks,omitempty"`

	// Resume token value to use in subsequent calls for continuation.
	Resume string `json:"resume,omitempty"`

	// Total number of items available.
	Total int32 `json:"total,omitempty"`
}
