/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SnapshotSnapshotExtended struct {

	// Alias name to create for this snapshot. If null, remove any alias.
	Alias string `json:"alias,omitempty"`

	// The Unix Epoch time the snapshot will expire and be eligible for automatic deletion.
	Expires int32 `json:"expires,omitempty"`

	// The user or system supplied snapshot name. This will be null for snapshots pending delete.
	Name string `json:"name,omitempty"`

	// The Unix Epoch time the snapshot was created.
	Created int32 `json:"created"`

	// True if the snapshot has one or more locks present see, see the locks subresource of a snapshot for a list of locks.
	HasLocks bool `json:"has_locks"`

	// The system ID given to the snapshot. This is useful for tracking the status of delete pending snapshots.
	Id int32 `json:"id"`

	// The /ifs path snapshotted.
	Path string `json:"path,omitempty"`

	// Percentage of /ifs used for storing this snapshot.
	PctFilesystem float32 `json:"pct_filesystem"`

	// Percentage of configured snapshot reserved used for storing this snapshot.
	PctReserve float32 `json:"pct_reserve"`

	// The name of the schedule used to create this snapshot, if applicable.
	Schedule string `json:"schedule,omitempty"`

	// The amount of shadow bytes referred to by this snapshot.
	ShadowBytes int32 `json:"shadow_bytes"`

	// The amount of storage in bytes used to store this snapshot.
	Size int32 `json:"size"`

	// Snapshot state.
	State string `json:"state"`

	// The ID of the snapshot pointed to if this is an alias.
	TargetId int32 `json:"target_id,omitempty"`

	// The name of the snapshot pointed to if this is an alias.
	TargetName string `json:"target_name,omitempty"`
}
