/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type StatisticsProtocol struct {

	// Abbreviated name of protocol.
	Name string `json:"name"`

	// External protocols are customer facing, internal protocols expose metrics for internal OneFS systems.
	Type_ string `json:"type"`
}
