/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type StatisticsHistoryStat struct {

	// Devid of node of statistic or 0 for cluster scoped statistics.
	Devid int32 `json:"devid"`

	// Key specific error string, if applicable.
	Error_ string `json:"error,omitempty"`

	// Key specific error number, if applicable.
	ErrorCode int32 `json:"error_code,omitempty"`

	// Key name of statistic.
	Key string `json:"key"`

	// The interval for which these results were figured (averaged against.)
	Resolution int32 `json:"resolution"`

	// Time-series values.
	Values []StatisticsHistoryStatValue `json:"values,omitempty"`
}
