/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type StoragepoolStatusUnprovisionedItem struct {

	// The drive bay number.
	Bay int32 `json:"bay"`

	// The node the drive is on.
	Lnn int32 `json:"lnn"`
}
