/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SubnetsSubnetPoolIface struct {

	// A string that defines an interface name.
	Iface string `json:"iface,omitempty"`

	// Logical Node Number.
	Lnn int32 `json:"lnn,omitempty"`
}
