/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SummaryDriveDriveItem struct {

	// The average operation latency.
	AccessLatency float32 `json:"access_latency"`

	// The rate of slow (long-latency) operations.
	AccessSlow float32 `json:"access_slow"`

	// The percentage of time the drive was busy.
	Busy float32 `json:"busy"`

	// The rate of bytes written.
	BytesIn float32 `json:"bytes_in"`

	// The rate of bytes read.
	BytesOut float32 `json:"bytes_out"`

	// Drive ID LNN:bay.
	DriveId string `json:"drive_id"`

	// The average time spent in the I/O scheduler.
	IoschedLatency float32 `json:"iosched_latency"`

	// The average length of the I/O scheduler queue.
	IoschedQueue float32 `json:"iosched_queue"`

	// Unix Epoch time in seconds of the request.
	Time int32 `json:"time"`

	// The type of the drive.
	Type_ string `json:"type"`

	// The percent of blocks used on the drive.
	UsedBytesPercent float32 `json:"used_bytes_percent"`

	// The number of inodes allocated on the drive.
	UsedInodes float32 `json:"used_inodes"`

	// The average size of write operations.
	XferSizeIn float32 `json:"xfer_size_in"`

	// The average size of read operations.
	XferSizeOut float32 `json:"xfer_size_out"`

	// The rate of write operations.
	XfersIn float32 `json:"xfers_in"`

	// The rate of read operations.
	XfersOut float32 `json:"xfers_out"`
}
