/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SummaryProtocolStatsProtocolStatsOnefs struct {

	// OneFS throughput in MB/s in.
	In float32 `json:"in"`

	// OneFS throughput in MB/s out.
	Out float32 `json:"out"`

	// OneFS throughput in MB/s total.
	Total float32 `json:"total"`
}
