/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SyncJobWorker struct {

	// Whether there is a connection between the source and target.
	Connected bool `json:"connected,omitempty"`

	// The last time a network split occurred.
	LastSplit int32 `json:"last_split,omitempty"`

	// The last time the worker performed work.
	LastWork int32 `json:"last_work,omitempty"`

	// The LIN being worked on.
	Lin int32 `json:"lin,omitempty"`

	// The lnn the worker is assigned to run on.
	Lnn int32 `json:"lnn,omitempty"`

	// The process ID of the worker.
	ProcessId int32 `json:"process_id,omitempty"`

	// The source host for this worker.
	SourceHost string `json:"source_host,omitempty"`

	// The target host for this worker.
	TargetHost string `json:"target_host,omitempty"`

	// The ID of the worker.
	WorkerId int32 `json:"worker_id,omitempty"`
}
