/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SyncJobPolicyFileMatchingPatternOrCriteriaItem struct {

	// An array containing individual file criterion objects each describing one criterion.  These are logically AND'ed together to form a set of criteria.
	AndCriteria []SyncJobPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem `json:"and_criteria,omitempty"`
}
