/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SyncJobPolicyFileMatchingPattern struct {

	// An array containing objects with \"and_criteria\" properties, each set of and_criteria will be logically OR'ed together to create the full file matching pattern.
	OrCriteria []SyncJobPolicyFileMatchingPatternOrCriteriaItem `json:"or_criteria,omitempty"`
}
