/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SyncRuleSchedule struct {

	// Start time (inclusive) for this schedule, during its specified days.  Format is \"hh:mm\" (24h format hour, and minute).  A null value indicates the beginning of the day (\"00:00\").
	Begin string `json:"begin,omitempty"`

	// End time (inclusive) for this schedule, during its specified days.  Format is \"hh:mm\" (three-letter weekday name abbreviation, 24h format hour, and minute).  A null value indicates the end of the day (\"23:59\").
	End string `json:"end,omitempty"`

	// If true, this rule is in effect on Friday.  If false, or unspecified, it is not.
	Friday bool `json:"friday,omitempty"`

	// If true, this rule is in effect on Monday.  If false, or unspecified, it is not.
	Monday bool `json:"monday,omitempty"`

	// If true, this rule is in effect on Saturday.  If false, or unspecified, it is not.
	Saturday bool `json:"saturday,omitempty"`

	// If true, this rule is in effect on Sunday.  If false, or unspecified, it is not.
	Sunday bool `json:"sunday,omitempty"`

	// If true, this rule is in effect on Thursday.  If false, or unspecified, it is not.
	Thursday bool `json:"thursday,omitempty"`

	// If true, this rule is in effect on Tuesday.  If false, or unspecified, it is not.
	Tuesday bool `json:"tuesday,omitempty"`

	// If true, this rule is in effect on Wednesday.  If false, or unspecified, it is not.
	Wednesday bool `json:"wednesday,omitempty"`
}
