/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SyncJobPolicyFileMatchingPatternOrCriteriaItemAndCriteriaItem struct {

	// For \"custom_attribute\" type criteria.  The file will match as long as the attribute named by \"field\" exists.  Default is true.
	AttributeExists bool `json:"attribute_exists,omitempty"`

	// If true, the value comparison will be case sensitive.  Default is true.
	CaseSensitive bool `json:"case_sensitive,omitempty"`

	// The name of the file attribute to match on (only required if this is a custom_attribute type criterion).  Default is an empty string \"\".
	Field string `json:"field,omitempty"`

	// How to compare the specified attribute of each file to the specified value.
	Operator string `json:"operator,omitempty"`

	// The type of this criterion, that is, which file attribute to match on.
	Type_ string `json:"type"`

	// The value to compare the specified attribute of each file to.
	Value string `json:"value,omitempty"`

	// If true, the attribute must match the entire word.  Default is true.
	WholeWord bool `json:"whole_word,omitempty"`
}
