/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type SyncSettingsSettings struct {

	// The per-worker burst socket memory constraint, in bytes.
	BurstMemoryConstraint int32 `json:"burst_memory_constraint,omitempty"`

	// The per-worker burst socket buffer coalesced data, in bytes.
	BurstSocketBufferSize int32 `json:"burst_socket_buffer_size,omitempty"`

	// NOTE: This field should not be changed without the help of Isilon support.  Default for the \"force_interface\" property that will be applied to each new sync policy unless otherwise specified at the time of policy creation.  Determines whether data is sent only through the subnet and pool specified in the \"source_network\" field. This option can be useful if there are multiple interfaces for the given source subnet.
	ForceInterface bool `json:"force_interface,omitempty"`

	// The max concurrent jobs that SyncIQ can support. This number is based on the size of the current cluster and the current SyncIQ worker throttle rule.
	MaxConcurrentJobs int32 `json:"max_concurrent_jobs,omitempty"`

	// Email sync reports to these addresses.
	ReportEmail []string `json:"report_email,omitempty"`

	// The default length of time (in seconds) a policy report will be stored.
	ReportMaxAge int32 `json:"report_max_age,omitempty"`

	// The default maximum number of reports to retain for a policy.
	ReportMaxCount int32 `json:"report_max_count,omitempty"`

	// Default for the \"restrict_target_network\" property that will be applied to each new sync policy unless otherwise specified at the time of policy creation.  If you specify true, and you specify a SmartConnect zone in the \"target_host\" field, replication policies will connect only to nodes in the specified SmartConnect zone.  If you specify false, replication policies are not restricted to specific nodes on the target cluster.
	RestrictTargetNetwork bool `json:"restrict_target_network,omitempty"`

	// If disabled, no RPO alerts will be generated.
	RpoAlerts bool `json:"rpo_alerts,omitempty"`

	// Specifies if the SyncIQ service currently on, paused, or off.  If paused, all sync jobs will be paused.  If turned off, all jobs will be canceled.
	Service string `json:"service,omitempty"`

	// Restricts replication policies on the local cluster to running on the specified subnet and pool.
	SourceNetwork *SyncPolicySourceNetwork `json:"source_network,omitempty"`

	// The interval (in seconds) in which treewalk syncs are forced to checkpoint.
	TwChkptInterval int32 `json:"tw_chkpt_interval,omitempty"`
}
