/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type TimezoneRegion struct {

	// Clarifying comments on the region or timezone.
	Comments string `json:"comments,omitempty"`

	// A unique identifier for the timezone region.
	Id string `json:"id,omitempty"`

	// The name of the region.
	Region string `json:"region,omitempty"`

	// A timezone.
	Timezone *TimezoneRegionTimezone `json:"timezone,omitempty"`
}
