/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// Change Password Request
type UserChangePassword struct {

	// Specifies user's new password
	NewPassword string `json:"new_password"`

	// User's expired password
	OldPassword string `json:"old_password"`
}
