/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

type WormSettingsSettings struct {

	// Specifies the current time of the SmartLock compliance clock in Unix Epoch seconds. If the compliance clock is not set, this value is null. A PUT request will set the compliance clock date to the current system time. The cluster must be in compliance mode to set the compliance clock.
	Cdate int32 `json:"cdate,omitempty"`
}
