/*
 * Isilon SDK
 *
 * Isilon SDK - Language bindings for the OneFS API
 *
 * API version: 5
 * Contact: sdk@isilon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package isi_sdk_8_1_0

// Specifies properties for access zones.
type Zone struct {

	// Specifies an alternate system provider.
	AlternateSystemProvider string `json:"alternate_system_provider,omitempty"`

	// Specifies the list of authentication providers available on this access zone.
	AuthProviders []string `json:"auth_providers,omitempty"`

	// Specifies amount of time in seconds to cache a user/group.
	CacheEntryExpiry int32 `json:"cache_entry_expiry,omitempty"`

	// Determines if a path is created when a path does not exist.
	CreatePath bool `json:"create_path,omitempty"`

	// Allow for overlapping base path.
	ForceOverlap bool `json:"force_overlap,omitempty"`

	// Specifies the permissions set on automatically created user home directories.
	HomeDirectoryUmask int32 `json:"home_directory_umask,omitempty"`

	// Specifies a list of users and groups that have read and write access to /ifs.
	IfsRestricted []AuthAccessAccessItemFileGroup `json:"ifs_restricted,omitempty"`

	// Maps untrusted domains to this NetBIOS domain during authentication.
	MapUntrusted string `json:"map_untrusted,omitempty"`

	// Specifies the access zone name.
	Name string `json:"name,omitempty"`

	// Specifies number of seconds the negative cache entry is valid.
	NegativeCacheEntryExpiry int32 `json:"negative_cache_entry_expiry,omitempty"`

	// Specifies the NetBIOS name.
	NetbiosName string `json:"netbios_name,omitempty"`

	// Specifies the access zone base directory path.
	Path string `json:"path,omitempty"`

	// Specifies the skeleton directory that is used for user home directories.
	SkeletonDirectory string `json:"skeleton_directory,omitempty"`

	// Specifies the system provider for the access zone.
	SystemProvider string `json:"system_provider,omitempty"`

	// Specifies the current ID mapping rules.
	UserMappingRules []string `json:"user_mapping_rules,omitempty"`
}
